// =============================================================================
//  AI FEATURE MODULE — PUBLIC ENTRY POINT
//  ai/index.ts
//
//  Single point of access for all AI capabilities in the OpenIdear application.
// =============================================================================

// ─── Provider Layer ──────────────────────────────────────────────────────────
export {
  type AIProvider,
  type AIMessage,
  type CompletionOptions,
  type TokenUsage,
  type AICompletion,
  type AIJSONResult,
  type AIErrorCode,
  AIError,
  GeminiProvider,
  ProviderRegistry,
  providerRegistry,
  FallbackStrategy,
  fallbackStrategy,
} from "./provider";

// ─── Prompt Layer ─────────────────────────────────────────────────────────────
export {
  PromptBuilder,
  type BuiltPrompt,
  PromptLoader,
  FilePromptSource,
  promptLoader,
  type PromptDefinition,
  type PromptSource,
  PromptRegistry,
  promptRegistry,
  PromptVersionManager,
  promptVersionManager,
} from "./prompt";

// ─── Context Layer ────────────────────────────────────────────────────────────
export {
  type AIContext,
  AIContextCollector,
  type EditorContext,
  EditorContextBuilder,
  type PublishingContext,
  PublishingContextBuilder,
  type GrowthContext,
  GrowthContextBuilder,
} from "./context";

// ─── Telemetry Layer ──────────────────────────────────────────────────────────
export {
  type AILogEntry,
  type AILogSink,
  type LoggedPrompt,
  type LoggedError,
  type TelemetryLogParams,
  ConsoleAILogSink,
  FileAILogSink,
  TelemetryLogger,
  aiLogger,
  calculateCost,
} from "./telemetry";

// ─── Configuration Layer ────────────────────────────────────────────────────────
export {
  type AIRetryConfig,
  type AIConfig,
  type AIConfigScope,
  AIConfigCenter,
  aiConfigCenter,
} from "./config";

// ─── Runtime Layer ────────────────────────────────────────────────────────────
export {
  AIRuntime,
  type RuntimeRequestOptions,
  aiRuntime,
} from "./runtime";

// ─── Execution Layer ──────────────────────────────────────────────────────────
export {
  type ExecutionPolicy,
  type ExecutionContext,
  type ExecutionResult,
  type ExecutionMiddleware,
  type ExecutionStage,
  type UserContext,
  type PromptContext,
  type ArticleContext,
  type SelectionContext,
  type EditorContextState,
  type PublishingContextState,
  type TelemetryMetadata,
  ExecutionContextContainer,
  MetricsMiddleware,
  TelemetryLoggingMiddleware,
  CacheMiddleware,
  BudgetMiddleware,
  SafetyMiddleware,
  JsonSelfHealingMiddleware,
  RetryMiddleware,
  ExecutionPipeline,
  ExecutionFacade,
  aiExecutionFacade,
} from "./execution";

// ─── Tool Layer ───────────────────────────────────────────────────────────────
export {
  type ToolPermission,
  type ToolContext,
  type ToolResult,
  type AITool,
  type ToolRegistryPlugin,
  type ExecutorOptions,
  type ToolUserContext,
  type ToolArticleContext,
  type ToolSelectionContext,
  type ToolWorkspaceContext,
  type ToolExecutionMetadata,
  ToolContextContainer,
  ToolRegistry,
  toolRegistry,
  ToolExecutor,
  toolExecutor,
  ReadPostTool,
  SearchPostTool,
  SearchMediaTool,
  SuggestTagsTool,
  GenerateSlugTool,
  SearchCategoryTool,
} from "./tool";

// ─── Agent Layer ──────────────────────────────────────────────────────────────
export {
  BaseAgent,
  type AgentOptions,
  type AgentResult,
  PlannerAgent,
  type PlannerInput,
  PlannerSchema,
  type PlannerOutline,
  WriterAgent,
  type WriterInput,
  WriterSchema,
  type WriterOutput,
  DiagramAgent,
  diagramAgent,
  type DiagramType,
  type DiagramRequest,
  type DiagramResult,
  EditorCopilot,
  editorCopilot,
  copilotActionRegistry,
  type CopilotAction,
  type ContinueInput,
  type ContinueOutput,
  type ImproveInput,
  type ImproveOutput,
  type ExampleInput,
  type ExampleOutput,
  type ReviewInput,
  type ReviewOutput,
  ContinueSchema,
  ImproveSchema,
  ExampleSchema,
  ReviewSchema,
  ImproveAgent,
  improveAgent,
  ExampleAgent,
  exampleAgent,
  ReviewAgent,
  reviewAgent,
} from "./agent";

// ─── Workflow Layer ───────────────────────────────────────────────────────────
export {
  Workflow,
  type WorkflowStage,
  CreateArticlePlanningWorkflow,
  CreateArticleWorkflow,
  AssetUploadWorkflow,
  type AssetUploadInput,
  EditingWorkflow,
  type EditingWorkflowInput,
  publishTaskRegistry,
  PublishingEngine,
  publishingEngine,
  MetadataResultSchema,
  type MetadataResult,
  ReviewResultSchema,
  type ReviewResult,
  SEOResultSchema,
  type SEOResult,
  CategoryResultSchema,
  type CategoryResult,
  PublishingWorkflow,
  type PublishingWorkflowInput,
  type PublishPreflightReport,
  growthTaskRegistry,
  GrowthEngine,
  growthEngine,
  FAQResultSchema,
  type FAQResult,
  InternalLinkResultSchema,
  type InternalLinkResult,
  ComparisonTableResultSchema,
  type ComparisonTableResult,
  SocialPostResultSchema,
  type SocialPostResult,
  AffiliateResultSchema,
  type AffiliateResult,
  ContentGapResultSchema,
  type ContentGapResult,
  GrowthWorkflow,
  type GrowthWorkflowInput,
  tutorialWorkflow,
  affiliateWorkflow,
  newsWorkflow,
  comparisonWorkflow,
  publishChecklistRegistry,
  PublishChecklistRegistry,
  type ChecklistItemResult,
  type PublishChecklistRule,
  publishingScheduler,
  PublishingScheduler,
  type PublishingStatus,
  type PublishingState,
  type PublishTransitionPayload,
  versionHistoryManager,
  VersionHistoryManager,
  type VersionType,
  type VersionEntry,
  postInsightsManager,
  PostInsightsManager,
  type ReadabilityMetrics,
  type PostInsightsResult,
  publishValidator,
  PublishValidator,
  type ValidationIssue,
  type ValidationOptions,
} from "./workflow";

// ─── Vision Layer ─────────────────────────────────────────────────────────────
export {
  aiVisionService,
  GeminiVisionProvider,
  OpenAIVisionProvider,
  ClaudeVisionProvider,
  AzureVisionProvider,
  type ImageAnalysisResult,
  type ImageAIProvider,
} from "./vision";

// ─── Orchestration Layer ──────────────────────────────────────────────────────
export {
  type RetryPolicy,
  type Task,
  type OrchestratedTask,
  type TaskResult,
  type StepRecord,
  type StepStatus,
  type StateCondition,
  type StepCondition,
  type AndCondition,
  type OrCondition,
  type NotCondition,
  type ConditionExpression,
  type StepDefinition,
  type WorkflowDefinition,
  type OrchestrationRegistryPlugin,
  ExecutionStateContainer,
  type ReadonlyExecutionState,
  type RunStatus,
  ConditionEvaluator,
  TaskRegistry,
  taskRegistry,
  WorkflowRegistry,
  workflowRegistry,
  OrchestratedWorkflow,
  ExecutionTask,
  type ExecutionTaskParams,
  OrchestrationPipeline,
  type PipelineRunOptions,
  type PipelineEventMap,
  OrchestrationResultBuilder,
  type OrchestrationResult,
  type StepSummary,
  type Workflow as OrchestrationWorkflow,
  type ExecutableWorkflow,
  type AlwaysCondition,
  type SuccessCondition,
  type FailureCondition,
  type CustomCondition,
  type CustomConditionEvaluatorFn,
  customConditionRegistry,
  CustomConditionRegistry,
} from "./orchestration";
