import { z } from "zod";
import type { PlannerOutline } from "./planner.schema";

// =============================================================================
//  WRITER AGENT — INPUT CONTRACT
// =============================================================================

/**
 * Strongly typed interface for the Writer Agent's inputs.
 */
export interface WriterInput extends Record<string, any> {
  /**
   * The structured plan output generated by the Planner Agent.
   * Reuse the PlannerOutline types (title, difficulty, estimatedReadingTime, keywords, outline).
   */
  readonly plan: PlannerOutline;

  /**
   * Optional custom directions passed by the user to refine the writing process.
   * e.g., "Add a code snippet showing TypeScript interfaces" or "Use active voice".
   */
  readonly additionalInstructions?: string;
}

// =============================================================================
//  WRITER AGENT — OUTPUT SCHEMA
// =============================================================================

/**
 * Controlled enum for allowed visual suggestion types.
 * Arbitrary values from LLM are strictly disallowed.
 */
export const VisualTypeEnum = z.enum([
  "illustration",
  "diagram",
  "screenshot",
  "product",
  "comparison",
  "chart",
  "code",
  "none",
]);

export type VisualType = z.infer<typeof VisualTypeEnum>;

/**
 * Zod validation schema for a structured visual suggestion.
 */
export const VisualSuggestionSchema = z.object({
  id: z.string().default(() => `vs_${Math.random().toString(36).substring(2, 7)}`),
  target: z.string(),
  position: z.string().default("after-heading"),
  visualType: VisualTypeEnum,
  searchQuery: z.string(),
  imagePrompt: z.string(),
  altText: z.string(),
  reason: z.string(),
  confidence: z.number().min(0).max(1).default(0.9),
});

export type VisualSuggestion = z.infer<typeof VisualSuggestionSchema>;

/**
 * Legacy Zod validation schema for backward-compatible image suggestions.
 */
export const ImageSuggestionSchema = z.object({
  heading: z.string(),
  searchQuery: z.string(),
  imagePrompt: z.string(),
  alt: z.string(),
  position: z.union([z.number(), z.string()]).optional(),
});

export type ImageSuggestion = z.infer<typeof ImageSuggestionSchema>;

/**
 * Base Zod schema definition for Writer response.
 */
const BaseWriterSchema = z.object({
  markdown: z.string(),
  wordCount: z.number().int().positive(),
  estimatedReadingTime: z.number().int().positive(),
  visualSuggestions: z.array(VisualSuggestionSchema).default([]),
  imageSuggestions: z.array(ImageSuggestionSchema).optional(),
});

/**
 * Transformed WriterSchema ensuring bidirectional compatibility between
 * visualSuggestions and imageSuggestions.
 */
export const WriterSchema = BaseWriterSchema.transform((data) => {
  const visualSuggestions = data.visualSuggestions || [];
  let imageSuggestions = data.imageSuggestions;

  // 1. If visualSuggestions present and imageSuggestions omitted, populate imageSuggestions
  if (visualSuggestions.length > 0 && (!imageSuggestions || imageSuggestions.length === 0)) {
    imageSuggestions = visualSuggestions
      .filter((v) => v.visualType !== "none")
      .map((v) => ({
        heading: v.target,
        searchQuery: v.searchQuery,
        imagePrompt: v.imagePrompt,
        alt: v.altText,
        position: v.position,
      }));
  }

  // 2. If legacy imageSuggestions present and visualSuggestions empty, populate visualSuggestions
  if ((!visualSuggestions || visualSuggestions.length === 0) && imageSuggestions && imageSuggestions.length > 0) {
    const derivedVisualSuggestions: VisualSuggestion[] = imageSuggestions.map((img, idx) => ({
      id: `vs_${String(idx + 1).padStart(3, "0")}`,
      target: img.heading,
      position: typeof img.position === "string" ? img.position : "after-heading",
      visualType: "illustration" as VisualType,
      searchQuery: img.searchQuery,
      imagePrompt: img.imagePrompt,
      altText: img.alt,
      reason: "Visual suggestion derived from section heading.",
      confidence: 0.92,
    }));
    return {
      ...data,
      visualSuggestions: derivedVisualSuggestions,
      imageSuggestions,
    };
  }

  return {
    ...data,
    visualSuggestions,
    imageSuggestions: imageSuggestions || [],
  };
});

/**
 * Strongly typed TypeScript interface representing the parsed and validated
 * output structure returned by the Writer Agent.
 */
export type WriterOutput = z.infer<typeof WriterSchema>;
