import { z } from "zod";
import type { PlannerOutline } from "./planner.schema";

// =============================================================================
//  WRITER AGENT — INPUT CONTRACT
// =============================================================================

/**
 * Strongly typed interface for the Writer Agent's inputs.
 */
export interface WriterInput extends Record<string, any> {
  /**
   * The structured plan output generated by the Planner Agent.
   * Reuse the PlannerOutline types (title, difficulty, estimatedReadingTime, keywords, outline).
   */
  readonly plan: PlannerOutline;

  /**
   * Optional custom directions passed by the user to refine the writing process.
   * e.g., "Add a code snippet showing TypeScript interfaces" or "Use active voice".
   */
  readonly additionalInstructions?: string;
}

// =============================================================================
//  WRITER AGENT — OUTPUT SCHEMA
// =============================================================================

/**
 * Zod validation schema representing the expected JSON response from the LLM model.
 */
export const WriterSchema = z.object({
  /**
   * The complete, compiled body content of the article written in valid Markdown.
   * This field must contain the H2 and H3 headings matching the plan exactly,
   * interspersed with detailed paragraphs and code blocks.
   */
  markdown: z.string(),

  /**
   * The total word count of the generated markdown text body (integer).
   * Used to audit document length targets.
   */
  wordCount: z.number().int().positive(),

  /**
   * The estimated reading time of the generated article in minutes (integer).
   * Calculated based on the resulting word count.
   */
  estimatedReadingTime: z.number().int().positive(),
});

/**
 * Strongly typed TypeScript interface representing the parsed and validated
 * output structure returned by the Writer Agent.
 */
export type WriterOutput = z.infer<typeof WriterSchema>;
