const mongoose = require("mongoose");

const { Schema } = mongoose;
const postSchema = new Schema(
  {
    _id: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    image: { type: mongoose.Schema.Types.ObjectId, ref: "media" },
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, unique: true, trim: true, lowercase: true },
    description: { type: String, default: "", trim: true },
    content: { type: String, required: true },
    text: { type: String, required: true },
    author: { type: mongoose.Schema.Types.ObjectId, ref: "user", required: true },
    category: { type: mongoose.Schema.Types.ObjectId, ref: "category" },
    tags: {
      type: [{ type: mongoose.Schema.Types.ObjectId, ref: "tag" }],
      default: []
    },
    published: { type: Boolean, default: false },
    views: { type: Number, default: 0 },
    likes: {
      type: [{ type: mongoose.Schema.Types.ObjectId, ref: "user" }],
      default: []
    },
    marked: {
      type: [{ type: mongoose.Schema.Types.ObjectId, ref: "user" }],
      default: []
    },
    comments: {
      type: [{ type: mongoose.Schema.Types.ObjectId, ref: "comment" }],
      default: []
    },
    isFreePreview: { type: Boolean, default: false },
    lessonType: { type: String, enum: ["video", "file", "text"], default: "text" },
    mediaContent: { type: mongoose.Schema.Types.ObjectId, ref: "media" },
    del_flag: {
      type: Number,
      default: 0
    },
    readtime: {
      type: Number,
      default: 0
    },

    // ─── Structured Article Fields (Sprint 1) ────────────────────────────
    // All fields below are additive and optional.
    // Existing documents without these fields continue to work unchanged.

    /**
     * Discriminator for content format.
     * - "html-v1"    : legacy HTML string stored in `content` (all existing posts)
     * - "blocks-v1"  : structured ArticleBlock[] stored in `blocks` (future AI articles)
     * Defaults to "html-v1" so new posts created by the existing editor remain HTML posts.
     */
    contentVersion: {
      type: String,
      enum: ["html-v1", "blocks-v1"],
      default: "html-v1",
    },

    /**
     * Structured article blocks. Only populated when contentVersion === "blocks-v1".
     * Each element is a typed ArticleBlock (paragraph, heading, callout, faq, etc.).
     * Stored as Mixed to remain schema-flexible during early iterations.
     */
    blocks: {
      type: [mongoose.Schema.Types.Mixed],
      default: undefined, // sparse — not written for html-v1 posts
    },

    /**
     * Article hero metadata for structured articles.
     */
    hero: {
      type: new Schema({
        title: { type: String },
        subtitle: { type: String },
        image: {
          type: new Schema({
            src: { type: String },
            alt: { type: String },
          }, { _id: false }),
        },
        category: { type: String },
        readingTime: { type: Number },
      }, { _id: false }),
      default: undefined,
    },

    /**
     * Persisted AI context: planner output, writer output, growth results.
     * Enables downstream re-generation, analytics, and structured article assembly.
     */
    aiContext: {
      type: new Schema({
        plannerOutput: { type: mongoose.Schema.Types.Mixed },
        writerOutput: {
          type: new Schema({
            wordCount: { type: Number },
            estimatedReadingTime: { type: Number },
          }, { _id: false }),
        },
        growthResults: { type: mongoose.Schema.Types.Mixed },
        generation: {
          type: new Schema({
            model: { type: String },
            generatedAt: { type: Date },
          }, { _id: false }),
        },
      }, { _id: false }),
      default: undefined,
    },

    /**
     * SEO metadata generated by the AI SEO task (Sprint 4+).
     */
    seo: {
      type: new Schema({
        metaTitle: { type: String },
        metaDescription: { type: String },
        keywords: { type: [String], default: undefined },
        canonicalUrl: { type: String },
        schemaOrg: {
          type: new Schema({
            article: { type: mongoose.Schema.Types.Mixed },
            faqPage: { type: mongoose.Schema.Types.Mixed },
          }, { _id: false }),
        },
      }, { _id: false }),
      default: undefined,
    },
  },
  {
    versionKey: '_somethingElse',
    timestamps: true,
  }
);

// Indexes for performance
postSchema.index({ author: 1, createdAt: -1 });
postSchema.index({ category: 1, createdAt: -1 });
postSchema.index({ published: 1, del_flag: 1, createdAt: -1 });
postSchema.index({ text: "text" }); // Full text search index

module.exports = mongoose.model("post", postSchema);
